name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Odoo addons
        run: |
          set -e
          echo "Stopping Odoo service..."
          sudo systemctl stop flint_international.service

          echo "Pulling latest code..."
          cd /home/flint_international/Programming/Odoo/odoo_17/env/flint_international/addons
          git pull origin master

          echo "Starting Odoo service..."
          sudo systemctl start flint_international.service
